DLF.auth = {
  render(page) {
    const register = page === 'register'; const { icon, brand, error, passwordField } = DLF.ui;
    document.querySelector('#app').innerHTML = `<main class="auth-layout" id="main"><aside class="auth-story">${brand()}<div class="auth-story-content"><span class="eyebrow">LOST THINGS. FOUND CONNECTIONS.</span><h1>A small act.<br>A big relief.</h1><p>That thing you’re looking for?<br>Someone on campus might have found it.</p><div class="auth-illustration"><img src="assets/images/backpack.svg" alt="Backpack illustration"><span class="auth-found">${icon('check')}Back where it belongs.</span></div><blockquote>“A connected campus makes all the difference.”</blockquote><span class="auth-story-footer">Built for your campus community.</span></div></aside><section class="auth-panel"><a class="back-link" href="index.html">← Back to home</a><div class="auth-form-container"><span class="auth-mobile-brand">${brand()}</span><div class="auth-heading"><div class="auth-symbol">${icon(register ? 'user' : 'heart')}</div><h2>${register ? 'Create Your Account' : 'Welcome Back'}</h2><p>${register ? 'Join a campus that looks out for each other.' : 'Login to continue to DigitalLostFound'}</p></div><form id="auth-form" novalidate>${register ? `<div class="field"><label for="name">Full Name</label><input id="name" name="name" autocomplete="name" placeholder="Nipuni Liyanage" maxlength="80" required>${error('name')}</div><div class="field"><label for="registration">Registration Number</label><input id="registration" name="registration" placeholder="EG/2023/XXXX" maxlength="40" required>${error('registration')}</div>` : ''}<div class="field"><label for="email">University Email</label><input id="email" type="email" name="email" autocomplete="email" placeholder="student@eng.ruh.ac.lk" maxlength="150" required>${error('email')}</div>${passwordField('Password', 'password', register ? 'new-password' : 'current-password')}${register ? `<p class="field-hint password-hint">Use at least 8 characters.</p>${passwordField('Confirm Password', 'confirmPassword', 'new-password')}` : `<div class="auth-options"><label class="checkbox-label"><input type="checkbox" name="remember">Remember Me</label><button class="text-button" type="button" id="forgot-password">Forgot Password?</button></div>`}<p class="form-error" id="auth-error" role="alert"></p><button class="btn btn-primary full-width" type="submit">${register ? 'Create Account' : 'Login'}${icon('arrow')}</button></form><p class="auth-switch">${register ? 'Already have an account? <a href="login.html">Login</a>' : 'Don’t have an account? <a href="register.html">Create Account</a>'}</p><div class="demo-notice">${icon('info')}<p><strong>Frontend demo</strong>${register ? 'Account details are saved in this browser. Passwords are never stored.' : 'Use any valid email and any nonempty password. Authentication is simulated.'}</p></div></div><p class="auth-copyright">© 2026 DigitalLostFound · Made for campus life</p></section></main>`;
    DLF.ui.bindPasswords();
    const form = document.querySelector('#auth-form');
    form.onsubmit = async event => {
      event.preventDefault();
      const rules = { email: DLF.ui.emailRule, password: register ? value => value.length >= 8 ? '' : 'Use at least 8 characters.' : DLF.ui.required('Password') };
      if (register) Object.assign(rules, { name: DLF.ui.required('Full name'), registration: DLF.ui.required('Registration number'), confirmPassword: value => value && value === form.elements.password.value ? '' : 'Passwords must match.' });
      if (!DLF.ui.validate(form, rules)) return;
      const button = event.submitter; button.disabled = true; document.querySelector('#auth-error').textContent = '';
      const values = Object.fromEntries(new FormData(form)); values.email = values.email.trim(); values.remember = form.elements.remember?.checked || false;
      try {
        if (register) { values.name = values.name.trim(); await DLF.api.registerUser(values); DLF.ui.flash('Account created. Log in to get started.'); location.href = 'login.html'; }
        else { await DLF.api.loginUser(values); location.href = 'dashboard.html'; }
      } catch (error) { document.querySelector('#auth-error').textContent = error.message; button.disabled = false; }
    };
    document.querySelector('#forgot-password')?.addEventListener('click', () => {
      DLF.ui.modal({ title: 'Reset your password', content: `<p>This prototype does not send email or store passwords. You can log in with any nonempty password.</p><div class="field"><label for="reset-email">University Email</label><input type="email" id="reset-email" autocomplete="email" value="${DLF.ui.escape(form.elements.email.value)}"></div>`, confirmText: 'Preview reset request', onConfirm: dialog => { const message = DLF.ui.emailRule(dialog.querySelector('input').value); if (message) throw new Error(message); DLF.ui.toast('Reset request previewed. No email was sent.'); } });
    });
  }
};
