DLF.dashboard = {
  async render() {
    const [user, items, reports, notes] = await Promise.all([DLF.api.getUser(), DLF.api.getItems(), DLF.api.getMyReports(), DLF.api.getNotifications()]);
    const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
    const { icon, escape, card } = DLF.ui;
    const lost = items.filter(item => item.type === 'lost' && item.status === 'Open').length;
    const found = items.filter(item => item.type === 'found' && item.status === 'Open').length;
    const returned = items.filter(item => item.status !== 'Open').length;
    document.querySelector('#main').innerHTML = `<div class="page-heading"><div><span class="eyebrow">YOUR CAMPUS AT A GLANCE</span><h2>${greeting}, ${escape(user.name.split(' ')[0])}! <span class="greeting-sun">✦</span></h2><p>Here’s what’s happening around campus.</p></div><span class="date-chip">${icon('calendar')}${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span></div><div class="dashboard-stats">${[['lost', 'Lost Items', lost, 'lost-items'], ['found', 'Found Items', found, 'found-items'], ['check', 'Items Returned', returned, 'search'], ['reports', 'My Reports', reports.length, 'my-reports']].map(([glyph, label, value, href]) => `<a class="stat-card ${glyph}" href="${href}.html${glyph === 'check' ? '?resolved=1' : ''}"><div><span>${label}</span><strong>${value}</strong><small>${glyph === 'reports' ? 'Your campus contributions' : glyph === 'check' ? 'Back where they belong' : 'Open campus reports'}</small></div><span class="stat-icon">${icon(glyph)}</span></a>`).join('')}</div><section class="dashboard-banner"><div><span class="eyebrow">LET’S BRING IT HOME</span><h3>Missing something? Found something?</h3><p>Your next report could make someone’s day.</p></div><div class="button-row"><a class="btn btn-primary" href="report-item.html?type=lost">${icon('plus')}Report Lost Item</a><a class="btn btn-outline" href="report-item.html?type=found">${icon('plus')}Report Found Item</a></div></section><div class="dashboard-columns"><section><div class="content-heading"><h3>Recent Reports <span class="subtle-count">${items.length}</span></h3><a class="text-link" href="search.html">View all ${icon('arrow')}</a></div><div class="items-grid dashboard-items">${items.slice(0, 6).map(item => card(item)).join('')}</div></section><aside><section class="panel activity-panel"><div class="content-heading"><h3>Recent Activity</h3><span class="status-dot"></span></div>${notes.length ? notes.slice(0, 4).map(note => `<a class="activity-entry" href="notifications.html"><span class="activity-icon">${icon(note.icon)}</span><div><strong>${escape(note.title)}</strong><p>${escape(note.message)}</p><small>${DLF.ui.date(note.date)}</small></div></a>`).join('') : '<p class="muted">Your updates will appear here as you use the app.</p>'}<a class="text-link activity-all" href="notifications.html">All notifications ${icon('arrow')}</a></section><section class="help-card">${icon('shield')}<h3>A safer way to reconnect</h3><p>Ask for a detail only the owner would know, and arrange handovers in a public campus location.</p><a class="text-link" href="found-items.html">Help someone find their item ${icon('arrow')}</a></section></aside></div>`;
  }
};
