DLF.items = {
  async list(type) {
    const { icon, escape, card } = DLF.ui;
    const params = new URLSearchParams(location.search); const initialQuery = params.get('q') || '';
    const items = await DLF.api.getItems();
    const title = type === 'lost' ? 'Lost Items' : type === 'found' ? 'Found Items' : 'Search Campus Items';
    const locations = [...new Set([...DLF.data.locations, ...items.map(item => item.location)])].sort();
    document.querySelector('#main').innerHTML = `<div class="page-heading"><div><span class="eyebrow">LET’S RECONNECT</span><h2>${title}</h2><p>${type ? `Browse items recently reported as ${type} on campus.` : 'Look for a name, category, color, location, or lost/found status.'}</p></div><a class="btn btn-primary" href="report-item.html${type ? `?type=${type}` : ''}">${icon('plus')}Report ${type ? `${type[0].toUpperCase()}${type.slice(1)}` : 'an'} Item</a></div><section class="panel filter-panel" aria-label="Search and filters"><form id="filter-form"><div class="list-search">${icon('search')}<label class="sr-only" for="item-search">Search ${type || 'all'} items</label><input type="search" id="item-search" name="query" placeholder="Search ${type || 'all'} items..." value="${escape(initialQuery)}"></div><div class="filter-row"><div class="field"><label for="category">Category</label><select id="category" name="category"><option value="">All categories</option>${DLF.data.categories.map(value => `<option>${value}</option>`).join('')}</select></div><div class="field"><label for="location">Location</label><select id="location" name="location"><option value="">All locations</option>${locations.map(value => `<option>${escape(value)}</option>`).join('')}</select></div><div class="field"><label for="date">Date ${type || 'reported'}</label><input id="date" type="date" name="date"></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option><option>Open</option><option>Returned</option><option>Resolved</option></select></div>${!type ? '<div class="field"><label for="type">Report type</label><select id="type" name="type"><option value="">Lost & found</option><option value="lost">Lost</option><option value="found">Found</option></select></div>' : ''}<button class="text-button clear-filters" type="reset">Clear filters</button></div></form></section><div class="results-heading"><span id="result-count" role="status" aria-live="polite"></span><span>${icon('filter')}Campus reports</span></div><div class="items-grid browse-grid" id="items-grid"></div>`;
    const form = document.querySelector('#filter-form');
    const draw = () => {
      const filters = Object.fromEntries(new FormData(form)); if (type) filters.type = type;
      let result = DLF.api.filterItems(items, filters);
      if (params.get('resolved') && !filters.status) result = result.filter(item => item.status !== 'Open');
      document.querySelector('#result-count').textContent = `${result.length} ${result.length === 1 ? 'item' : 'items'} found`;
      document.querySelector('#items-grid').innerHTML = result.length ? result.map(item => card(item, { full: true })).join('') : DLF.ui.empty('No items found', 'Try another keyword or clear a filter to broaden your search.');
    };
    form.addEventListener('input', draw); form.addEventListener('change', draw);
    form.onsubmit = event => { event.preventDefault(); draw(); };
    form.addEventListener('reset', event => { event.preventDefault(); [...form.elements].forEach(field => { if (field.tagName === 'INPUT' || field.tagName === 'SELECT') field.value = ''; }); params.delete('resolved'); draw(); });
    draw();
  },
  async details() {
    const item = await DLF.api.getItem(new URLSearchParams(location.search).get('id'));
    const main = document.querySelector('#main'); const { icon, escape } = DLF.ui;
    if (!item) { main.innerHTML = DLF.ui.empty('Item not found', 'This report may have been deleted or the link is incomplete.', '<a class="btn btn-primary" href="index.html#recent-items">Browse recent items</a>'); return; }
    const loggedIn = !!DLF.api.getSession(); const own = loggedIn && item.ownerId === DLF.api.getSession().id;
    main.innerHTML = `<a class="back-link" href="${loggedIn ? `${item.type}-items.html` : 'index.html#recent-items'}">← Back to ${item.type} items</a><div class="detail-layout"><div class="detail-image"><img src="${DLF.ui.safeImage(item.image)}" alt="${escape(item.name)}"><span class="image-caption">${item.image.startsWith('data:') ? 'Photo provided by the reporter' : 'Illustration · Sample campus report'}</span></div><article class="detail-content"><div class="detail-badges">${DLF.ui.badge(item)}</div><h2>${escape(item.name)}</h2><p class="detail-reference">REPORT #${item.id} · ${item.type === 'lost' ? 'Help bring it back home' : 'Looking for its owner'}</p><dl class="detail-facts"><div><dt>Category</dt><dd>${escape(item.category)}</dd></div><div><dt>Color</dt><dd>${escape(item.color || 'Not specified')}</dd></div><div><dt>Location ${item.type}</dt><dd>${escape(item.location)}</dd></div><div><dt>Date ${item.type}</dt><dd>${DLF.ui.date(item.date)}</dd></div><div><dt>Status</dt><dd><span class="status-dot"></span>${escape(item.status)}</dd></div></dl><h3>Description</h3><p class="detail-description">${escape(item.description)}</p><div class="reporter"><span class="avatar">${icon('user')}</span><div><strong>${own ? 'Reported by you' : 'Campus community member'}</strong><small>Personal contact information is kept private.</small></div>${icon('shield')}</div><div class="detail-actions">${item.status === 'Open' ? `${item.type === 'found' && !own ? `<button class="btn btn-primary" id="claim-item">${icon('check')}Claim Item</button>` : ''}<button class="btn ${item.type === 'lost' ? 'btn-primary' : 'btn-outline'}" id="contact-reporter">${icon('mail')}Contact Reporter</button>${item.type === 'lost' ? '<a class="btn btn-outline" href="possible-matches.html">Possible Match</a>' : ''}` : '<p class="notice">This report has been resolved. Thank you for helping your campus community.</p>'}${own ? `<a class="btn btn-outline" href="report-item.html?edit=${item.id}">${icon('edit')}Edit Report</a>` : ''}</div><div class="notice">${icon('shield')}Verify identifying details and meet in a public campus location.</div></article></div>`;
    document.querySelector('#contact-reporter')?.addEventListener('click', () => DLF.ui.contact(item.id));
    document.querySelector('#claim-item')?.addEventListener('click', () => {
      if (!loggedIn) { location.href = 'login.html'; return; }
      DLF.ui.modal({ title: 'Is this your item?', content: `<p>Help the reporter verify that <strong>${escape(item.name)}</strong> belongs to you. Describe a unique mark, contents, or another identifying detail.</p><div class="field"><label for="proof">Proof of ownership</label><textarea id="proof" rows="4" maxlength="1500" placeholder="Something only the owner would know..."></textarea><span class="field-hint">At least 15 characters. Do not include passwords or sensitive ID numbers.</span></div><div class="notice">${icon('info')}This demo claim is saved locally and is not sent to a reporter.</div>`, confirmText: 'Submit demo claim', onConfirm: async dialog => { await DLF.api.claimItem(item.id, dialog.querySelector('#proof').value); DLF.ui.toast('Demo claim submitted. Track its status in Notifications.'); await DLF.ui.updateUnread(); } });
    });
  },
  async matches() {
    const matches = await DLF.api.getMatches(); const { icon, escape } = DLF.ui;
    document.querySelector('#main').innerHTML = `<div class="page-heading"><div><span class="eyebrow">A STEP CLOSER TO HOME</span><h2>Possible Matches</h2><p>These found items might be what you’re looking for.</p></div><span class="date-chip">${icon('match')}${matches.length} possible ${matches.length === 1 ? 'match' : 'matches'}</span></div><div class="notice matches-notice">${icon('info')}These are sample matches for your reports. Compare the details before contacting the reporter.</div><div class="matches-list">${matches.length ? matches.map(match => `<article class="panel match-panel"><div class="match-heading"><span class="match-label">${icon('match')}Worth a closer look</span><span class="muted">Sample match</span></div><div class="match-pair">${[[match.lost, 'YOUR LOST ITEM'], [match.found, 'POSSIBLE FOUND ITEM']].map(([item, label]) => `<div class="match-item"><span class="eyebrow">${label}</span><div><img src="${DLF.ui.safeImage(item.image)}" alt="${escape(item.name)}"><div><h3>${escape(item.name)}</h3><p>${escape(item.color)}</p><p class="item-meta">${icon('pin')}${escape(item.location)}</p><small>${DLF.ui.date(item.date)}</small></div></div></div>`).join('')}<span class="match-connector">${icon('match')}</span></div><div class="match-reasons"><span>${icon('check')}Similar Item Name</span><span>${icon('check')}Same Color</span><span>${icon('check')}Nearby Location</span></div><div class="match-actions"><a class="btn btn-primary" href="item-details.html?id=${match.found.id}">View Found Item ${icon('arrow')}</a><button class="btn btn-outline" data-contact="${match.found.id}">Contact Reporter</button><button class="text-button" data-dismiss="${match.id}">Not My Item</button></div></article>`).join('') : DLF.ui.empty('No possible matches right now', 'Browse found items or add a report. The demo has preset matches for the sample user.', '<a class="btn btn-primary" href="found-items.html">Browse Found Items</a>')}</div>`;
    document.querySelectorAll('[data-contact]').forEach(button => button.onclick = () => DLF.ui.contact(button.dataset.contact));
    document.querySelectorAll('[data-dismiss]').forEach(button => button.onclick = async () => { await DLF.api.dismissMatch(button.dataset.dismiss); await DLF.items.matches(); DLF.ui.toast('Match dismissed.'); });
  }
};
