DLF.notifications = {
  async render() {
    const notes = await DLF.api.getNotifications(); const unread = notes.filter(note => !note.read).length;
    const { icon, escape, date } = DLF.ui;
    document.querySelector('#main').innerHTML = `<div class="page-heading"><div><span class="eyebrow">STAY IN THE LOOP</span><h2>Notifications ${unread ? `<span class="heading-count">${unread}</span>` : ''}</h2><p>Your matches, claims, and campus updates, all in one place.</p></div><button class="btn btn-outline" id="mark-all" ${!unread ? 'disabled' : ''}>${icon('check')}Mark All as Read</button></div><div class="notice matches-notice">${icon('info')}You’re viewing demo notifications. Live campus updates will be connected in a future version.</div><section class="panel notification-list" aria-label="Your notifications">${notes.length ? notes.map(note => `<article class="notification-row ${!note.read ? 'unread' : ''}"><span class="notification-icon ${note.icon}">${icon(note.icon)}</span><div class="notification-copy"><h3>${escape(note.title)}${!note.read ? '<span class="unread-dot" aria-label="Unread"></span>' : ''}</h3><p>${escape(note.message)}</p><time datetime="${escape(note.date)}">${date(note.date)} · ${new Date(note.date).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}</time><div class="notification-actions">${note.itemId ? `<a href="item-details.html?id=${note.itemId}" class="text-link" data-read-link="${note.id}">View item ${icon('arrow')}</a>` : ''}${!note.read ? `<button class="text-button" data-read="${note.id}">Mark as read</button>` : '<span class="read-label">Read</span>'}</div></div></article>`).join('') : DLF.ui.empty('You’re all caught up', 'Updates on your reports and demo claims will appear here.')}</section>`;
    document.querySelector('#mark-all').onclick = async () => { await DLF.api.markNotificationsRead(); await DLF.notifications.render(); await DLF.ui.updateUnread(); DLF.ui.toast('All notifications marked as read.'); };
    document.querySelectorAll('[data-read]').forEach(button => button.onclick = async () => { await DLF.api.markNotificationsRead(button.dataset.read); await DLF.notifications.render(); await DLF.ui.updateUnread(); });
    document.querySelectorAll('[data-read-link]').forEach(link => link.onclick = async event => { event.preventDefault(); await DLF.api.markNotificationsRead(link.dataset.readLink); location.href = link.href; });
  }
};
